# Pandas
* Collection of instruments/methods for data processing
* Fundamental: Two-dimensional (row and column) tabular data (DataFrame)
* Important subtype: Series - one-dimensional data with an index
* We can in many ways think of Pandas' data structures as NumPy arrays augmented with some extra functionality

# Series I
* One-dimensional data
* Data is labeled with an index
* Series consist of pairs (index, data)

In [1]:
import pandas as pd
a = pd.Series([4, 2, 7, 8, 4, 4])
a

0    4
1    2
2    7
3    8
4    4
5    4
dtype: int64

In [2]:
a[2]

7

In [3]:
a*2 + 4

0    12
1     8
2    18
3    20
4    12
5    12
dtype: int64

In [4]:
a.unique()

array([4, 2, 7, 8])

In [5]:
a.isin([2, 4])

0     True
1     True
2    False
3    False
4     True
5     True
dtype: bool

# Series II
* Indexing using non-integer-based indexing

In [ ]:
a = pd.Series([4, 2, 7, 8], index=['Spring', 'Summer', 'Autumn', 'Winter'])
a

In [ ]:
a['Winter']

### Exercise
* Modify the time series
$$(\text{Spring}, 4 ), (\text{Summer}, 2 ), (\text{Autumn}, 7), (\text{Winter}, 8)$$
such that all data is increased by 10%

In [7]:
a = a * 1.1

In [9]:
a = pd.Series([4, 2, 7, 8], index=['Spring', 'Summer', 'Autumn', 'Winter'])
a = a*1.1

# Date/Time series
* Extensive support for date-/time-type series of data
* Convert times/dates from other external formats
* Create times/dates as `DatetimeIndex`

In [10]:
dti = pd.to_datetime(['Jan 2018', 'Feb 2018', 'Mar 2018', 'Apr 2018', 'May 2018', 'Jun 2018', 'Jul 2018', 'Aug 2018', 'Sep 2018', 'Oct 2018', 'Nov 2018', 'Dec 2018'])
dti

DatetimeIndex(['2018-01-01', '2018-02-01', '2018-03-01', '2018-04-01',
               '2018-05-01', '2018-06-01', '2018-07-01', '2018-08-01',
               '2018-09-01', '2018-10-01', '2018-11-01', '2018-12-01'],
              dtype='datetime64[ns]', freq=None)

In [11]:
temps_2018 = pd.Series(data=[2.3, -.7, .3, 8.4, 15.0, 16.5, 19.2, 17.5, 14.1, 10.3, 5.9, 4.3], index=dti)
temps_2018

2018-01-01     2.3
2018-02-01    -0.7
2018-03-01     0.3
2018-04-01     8.4
2018-05-01    15.0
2018-06-01    16.5
2018-07-01    19.2
2018-08-01    17.5
2018-09-01    14.1
2018-10-01    10.3
2018-11-01     5.9
2018-12-01     4.3
dtype: float64

In [24]:
dti = pd.date_range(start='2nd Jan 2018', end='2nd Dec 2018')
dti

DatetimeIndex(['2018-01-02', '2018-01-03', '2018-01-04', '2018-01-05',
               '2018-01-06', '2018-01-07', '2018-01-08', '2018-01-09',
               '2018-01-10', '2018-01-11',
               ...
               '2018-11-23', '2018-11-24', '2018-11-25', '2018-11-26',
               '2018-11-27', '2018-11-28', '2018-11-29', '2018-11-30',
               '2018-12-01', '2018-12-02'],
              dtype='datetime64[ns]', length=335, freq='D')

`DatetimeIndex` is the standard object type for storing date/time series. Often used as index for `Series`.

# DataFrame
1. Forming
2. Pretty-printing
3. Slicing columns and selecting

In [25]:
data = [['Henrik Pedersen', 42, 'Associate Professor'], 
        ['Susanne Smed', 49, 'Professor'], 
        ['Kirstine Bak', 27, 'ph.d.-student'],
        ['Hans Hansen', 55, 'Professor']]
a = pd.DataFrame(data, columns=['Name', 'Age', 'Category'])

In [26]:
a

Name  Age             Category
0  Henrik Pedersen   42  Associate Professor
1     Susanne Smed   49            Professor
2     Kirstine Bak   27        ph.d.-student
3      Hans Hansen   55            Professor

In [27]:
a.shape

(4, 3)

In [28]:
a['Name']  #or a.Name

0    Henrik Pedersen
1       Susanne Smed
2       Kirstine Bak
3        Hans Hansen
Name: Name, dtype: object

## Slicing rows and selecting columns

In [29]:
a[2:4]

Name  Age       Category
2  Kirstine Bak   27  ph.d.-student
3   Hans Hansen   55      Professor

In [30]:
a.loc[2:4, 'Age']   # this is a view

2    27
3    55
Name: Age, dtype: int64

In [31]:
a[2:4]['Age']    # this is view or a copy - we don't know

2    27
3    55
Name: Age, dtype: int64

## Difference between a view and a copy

In [32]:
a[2:4]['Age'] += 1
a

/tmp/ipykernel_3739/2581885168.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a[2:4]['Age'] += 1


Name  Age             Category
0  Henrik Pedersen   42  Associate Professor
1     Susanne Smed   49            Professor
2     Kirstine Bak   28        ph.d.-student
3      Hans Hansen   56            Professor

In [34]:
a.loc[2:4, 'Age'] += 1
a

Name  Age             Category
0  Henrik Pedersen   42  Associate Professor
1     Susanne Smed   49            Professor
2     Kirstine Bak   30        ph.d.-student
3      Hans Hansen   58            Professor

## Manipulation and arithmetic

In [35]:
a['Age'] += 1

In [36]:
a['Compensation'] = [44000, 66000, 30000, 65000]

In [37]:
a

Name  Age             Category  Compensation
0  Henrik Pedersen   43  Associate Professor         44000
1     Susanne Smed   50            Professor         66000
2     Kirstine Bak   31        ph.d.-student         30000
3      Hans Hansen   59            Professor         65000

## Membership and comparison

In [38]:
a.Category.isin(['Professor'])

0    False
1     True
2    False
3     True
Name: Category, dtype: bool

In [39]:
a[a.Category.isin(['Professor'])]

Name  Age   Category  Compensation
1  Susanne Smed   50  Professor         66000
3   Hans Hansen   59  Professor         65000

In [49]:
a[a.Compensation > 50000]

Name  Age   Category  Compensation
1  Susanne Smed   50  Professor         66000
3   Hans Hansen   59  Professor         65000

In [50]:
del a['Compensation']
a

Name  Age             Category
0  Henrik Pedersen   43  Associate Professor
1     Susanne Smed   50            Professor
2     Kirstine Bak   31        ph.d.-student
3      Hans Hansen   59            Professor

## Index functionalities

In [51]:
a.reindex([1,3,0,2])

Name  Age             Category
1     Susanne Smed   50            Professor
3      Hans Hansen   59            Professor
0  Henrik Pedersen   43  Associate Professor
2     Kirstine Bak   31        ph.d.-student

In [52]:
a.sort_values('Age')

Name  Age             Category
2     Kirstine Bak   31        ph.d.-student
0  Henrik Pedersen   43  Associate Professor
1     Susanne Smed   50            Professor
3      Hans Hansen   59            Professor

## Exercise
* Give all with a compensation less than 50000 a raise of 1000 (Hint: use loc)

(restore `a`:)

In [67]:
a['Compensation'] = [44000, 66000, 30000, 65000]
a.loc[a.Compensation < 50000, 'Compensation'] += 1000
a

Name  Age             Category  Compensation
0  Henrik Pedersen   43  Associate Professor         45000
1     Susanne Smed   50            Professor         66000
2     Kirstine Bak   31        ph.d.-student         31000
3      Hans Hansen   59            Professor         65000

In [ ]:
i = a['Compensation'] < 50000
a.loc[i, 'Compensation'] += 1000
a

# Statistics
* First-order

In [71]:
a.mean(numeric_only=True)

Age                45.75
Compensation    51750.00
dtype: float64

In [72]:
a.Age.mean()

45.75

In [74]:
a.median(numeric_only=True)

Age                46.5
Compensation    55000.0
dtype: float64

In [76]:
def midrange(x):
    return x.min() + 0.5*(x.max()-x.min())
midrange(a.Age)

45.0

## Second-order statistics
Pearson correlation coefficient
$$ r_{xy} = \frac{\sum_{i=1}^n (x_i - \bar x)(y_i - \bar y)}{\sqrt{\sum_{i=1}^n (x_i - \bar x)}\sqrt{\sum_{i=1}^n (yi - \bar y)}}$$

In [77]:
a['Compensation'] = [44000, 66000, 30000, 65000]
a.corr(numeric_only=True)

/tmp/ipykernel_3739/737036983.py:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  a.corr()


Age  Compensation
Age           1.000000      0.936351
Compensation  0.936351      1.000000

In [79]:
a.cov(numeric_only=True)

Age  Compensation
Age              139.583333  1.927500e+05
Compensation  192750.000000  3.035833e+08

# Not available (na) and Not A Number (NaN)
* Missing data
* Operations not "well-defined"

In [90]:
a['Compensation'] *= pd.Series([1.02, 1.03, 1.04])

In [91]:
a

Name  Age             Category  Compensation
0  Henrik Pedersen   43  Associate Professor       45777.6
1     Susanne Smed   50            Professor       69339.6
2     Kirstine Bak   31        ph.d.-student       31824.0
3      Hans Hansen   59            Professor           NaN

In [92]:
b = a.dropna()
b

Name  Age             Category  Compensation
0  Henrik Pedersen   43  Associate Professor       45777.6
1     Susanne Smed   50            Professor       69339.6
2     Kirstine Bak   31        ph.d.-student       31824.0

In [83]:
a.fillna(0) # Be careful here - mini-asignment!

Name  Age             Category  Compensation
0  Henrik Pedersen   43  Associate Professor       44880.0
1     Susanne Smed   50            Professor       67980.0
2     Kirstine Bak   31        ph.d.-student       31200.0
3      Hans Hansen   59            Professor           0.0

In [96]:
# Reset our dataframe
a.loc[3, 'Compensation'] = 65000*1.02
a

Name  Age             Category  Compensation
0  Henrik Pedersen   43  Associate Professor       44880.0
1     Susanne Smed   50            Professor       67320.0
2     Kirstine Bak   31        ph.d.-student       30600.0
3      Hans Hansen   59            Professor       66300.0

## Exercise
1. Compute the mean compensation with values: a['Compensation'] = [44000, 66000, 30000, 65000]
2. Update compensation: a['Compensation'] *= pd.Series([1.02, 1.02, 1.02])
3. Compute mean compensation - is it increased by 2% ?
4. Update NA values using a.fillna(0, inplace=True)
5. Compute mean compensation - what do you observe? - why?

In [98]:
a['Compensation'] = [44000, 66000, 30000, 65000]

In [99]:
a['Compensation'] *= pd.Series([1.02, 1.02, 1.02])
a

Name  Age             Category  Compensation
0  Henrik Pedersen   43  Associate Professor       44880.0
1     Susanne Smed   50            Professor       67320.0
2     Kirstine Bak   31        ph.d.-student       30600.0
3      Hans Hansen   59            Professor           NaN

In [100]:
a['Compensation'].mean()

47600.0

In [103]:
a.fillna(0, inplace=True)
a

Name  Age             Category  Compensation
0  Henrik Pedersen   43  Associate Professor       44880.0
1     Susanne Smed   50            Professor       67320.0
2     Kirstine Bak   31        ph.d.-student       30600.0
3      Hans Hansen   59            Professor           0.0

In [104]:
a['Compensation'].mean()

35700.0

# Categorical Data
We can work more explicitly with categorical data in Pandas.
- Define categorical variable as a special kind of `Series`
- Categorical variables can be ordered or un-ordered

In [105]:
pd.Categorical(a['Category'],
               categories=['ph.d.-student', 'Associate Professor', 'Professor'],
               ordered=True)

['Associate Professor', 'Professor', 'ph.d.-student', 'Professor']
Categories (3, object): ['ph.d.-student' < 'Associate Professor' < 'Professor']

In [112]:
c = a.copy()
c['Category'] = pd.Categorical(a['Category'],
               categories=['Professor',  'Associate Professor', 'ph.d.-student'],
               ordered=True)

In [113]:
c.sort_values(['Category', 'Compensation'], ascending=False)

Name  Age             Category  Compensation
2     Kirstine Bak   31        ph.d.-student       30600.0
0  Henrik Pedersen   43  Associate Professor       44880.0
1     Susanne Smed   50            Professor       67320.0
3      Hans Hansen   59            Professor           0.0

# Writing and reading data with Pandas
* HDF5
* Parquet
* CSV
* XLSX (Excel)
* JSON
* SAS
* Stata

See more here: <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>

## Write a simple csv file
* emplyees.csv

In [114]:
a.to_csv('employees.csv')

## Reading a simple csv file


In [119]:
df_new = pd.read_csv('employees.csv', index_col=['Age','Category'])
df_new.sort_index()

Unnamed: 0             Name  Compensation
Age Category                                                      
31  ph.d.-student                 2     Kirstine Bak       30600.0
43  Associate Professor           0  Henrik Pedersen       44880.0
50  Professor                     1     Susanne Smed       67320.0
59  Professor                     3      Hans Hansen           0.0

Converting Pandas data to NumPy format

In [120]:
import numpy as np

np.asarray(df_new['Compensation'])

array([44880., 67320., 30600.,     0.])

or:

In [121]:
df_new['Compensation'].to_numpy()

array([44880., 67320., 30600.,     0.])

## Saving in binary format
* A good choice of data format for large datasets (Parquet); requires the `pyarrow` package.

In [123]:
a.to_parquet('employees.parquet')

- Another alternative (HDF5)

In [125]:
a.to_hdf('employees.h5', key='employees')

In [128]:
%ls  -al --block-size=K | grep employ

-rw-r--r-- 1 shei shei    1K Jun 13 13:33 employees.csv
-rw-r--r-- 1 shei shei 1042K Jun 13 13:40 employees.h5
-rw-r--r-- 1 shei shei    4K Jun 13 13:39 employees.parquet


See also overview of several options here: [Towards Data Science - The best format to save Pandas](https://towardsdatascience.com/the-best-format-to-save-pandas-data-414dca023e0d)

## Exercise
* Try saving data to a data format of your choice.
* Try open the data in the new format - is it as expected?

# Useful alternatives to Pandas

- **Polars**  
  Newer but similar dataframe tool. Written in Rust with a Python interface. Considerably faster processing of data than Pandas.  
  Try this if you often find Pandas slow to work with: <https://www.pola.rs/>
- **Dask**  
  More or less drop-in replacement for Pandas, NumPy, and other functionality that can process data across multiple CPU cores and distributed across multiple computers.  
  *A topic in the course on Thursday-Friday.*  
  Try this if you sometimes find that your data is too large for Pandas to handle: <https://www.dask.org/>

### References

- Fabio Nelli (2015) "Python Data Analytics", Apress, ISBN-13 (electronic): 978-1-4842-0958-5

- Wes McKinney & PyData Development Team (2018) "Pandas: powerful Python data analysis toolkit"